---
- hosts: 172.31.15.39
  become: yes
  task:
    - name: i want to execute the linux command diretly
      command: hostname
      register: myresults
    - name: i want to display my result
      debug:
        msg: "{{myresults}}"