---
- hosts: 172.31.15.39
  become: yes
  tasks:
   - name: i wnat to install git
     apt:
      name: git
      statee: present
     
   - name: i wnat to install tree
     apt:
      name: tree
      state: present