---
- hosts: 172.31.15.39
  become: yes
  tasks:
   - include_tasks: file.yml

   - name: i want to install webserver
     apt:
      name: apache2
      state: present

   - name: i want to install webserver
     service:
      name: apache2
      state: started   
      
   - name: i want to copy myindex.j2 into nodesite
     template:
      src: myindex.j2
      dest: var/www/html/index.html

  