---
- hosts: mywebservers
  become: yes
  tasks: 
   - name: i want to install webserver on debian node only
     apt:
      name: "{mywebpackageforubunntu}}"
      state: present
     when: ansible_os_family=="Debian"

   - name: i want to install webserver on redhat node only
     yum:
      name: "{{mywebpackageforredhat}}"
      state: present 
     when: ansible_os_family=="RedHat"  
